### ISSUE TITLE
Slovenian (sl_SI)

### ISSUE THREAD

**Issue by davidsupan** [YOURLS/YOURLS.pot#23]
Hi,

I've prepared translations for the Slovenian language:

https://supan.si/gogs/davidsupan/yourls_trans/raw/master/zip/yourls-1.7.1-sl_SI.zip

**Comment by ozh** [comment]
Hi there
Can I have a link to a directory or a repo instead of the archive itself? This way, when/if you update the translation, I wont have to update links. Thanks!

**Comment by davidsupan** [comment]
https://supan.si/gogs/davidsupan/yourls_trans Here you go.

**Comment by ozh** [comment]
Added! You should consider adding a readme or a description so that the average user knows what file to get and where to put it.
