### ISSUE TITLE
Translation for pt-BR available

### ISSUE THREAD

**Issue by henriquecrang** [YOURLS/YOURLS.pot#26]
I created a translation for Brazilian Portuguese in: https://github.com/henriquecrang/YOURLS.pot

**Comment by ozh** [comment]
Nice job. To avoid confusion though, the repo shouldn't be named "YOURLS.pot" or contain the `yourls.pot` file, since this is the *template* file. It should only contain translation files (ie .po and .mo)

**Comment by ozh** [comment]
Note that there is already a pt_BR translation: https://github.com/didi3d/YOURLS-pt_BR, is yours different/better/anything?

**Comment by henriquecrang** [comment]
Hi @ozh ! 

I'll change my rep following your sugestions.

I haven't noticed that there was already a pt_BR translation! I looked for it but only found a European Portuguese version.

**Comment by ozh** [comment]
Missed this followup, added to the list. Maybe consider adding instruction on how to use the file (example: https://github.com/KubaCZ721/YOURLS-cs_CZ)
