### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by ggardin** [YOURLS/YOURLS.pot#32]
Hello, I made a [new Italian translation](https://github.com/ggardin/YOURLS-it_IT) (`it_IT` locale) for YOURLS 1.7+.
An Italian translation was already listed in [Awesome YOURLS](https://github.com/YOURLS/awesome-yourls#translations) page, but I was not able to download it (says `error 401`) so I decided to translate it on my own.
I hope this will be helpful.

**Thanks for your great work**!
Have a nice day.

**Comment by ozh** [comment]
Could you make a pull request on https://github.com/YOURLS/awesome-yourls ? Thanks!

**Comment by ggardin** [comment]
Done :)
