### ISSUE TITLE
Telugu Translation for YOURLS

### ISSUE THREAD

**Issue by kalyan4786** [YOURLS/YOURLS.pot#34]
Hi,
I translated YOURLS to Telugu uploaded the language files to [Github](https://github.com/kalyan4786/YOURLS_Telugu_Translation).
You can now add it to supported languages.
Thanks in Advance 😇 

Thanks for this opensource project too. 👍  @ozh and team
Regards,
Kalyan Gupta

**Comment by ozh** [comment]
Neat! From the README:

## Awesome! How do I make my translation available to all?

When your translation file is all fine, make sure others can benefit from you hard work!

1. Upload your two `PO` and `MO` files somewhere on the interweb.  
It's best to use a *source control service*, such as Github or GitLab: this will make your changes easy to track, your files easy to maintain, and others' contributions easy to implement. If you don’t want to use SVN or Git, a regular hosting (your blog) will be OK  
2. Make it clear for users: a directory with clearly labelled files (`yourls-1.6-pt_BR.zip` for instance) so they know what to pick.  
3. Open a pull request on https://github.com/YOURLS/awesome-yourls and get your translation listed!   

## What are the available languages already?

See https://github.com/YOURLS/awesome-yourls

**Comment by kalyan4786** [comment]
see now i have updated the [repo](https://github.com/kalyan4786/YOURLS-te_IN/)
The translation still not available in Yourls supported languages.It's _Telugu_

**Comment by ozh** [comment]
Again: please open a pull request on https://github.com/YOURLS/awesome-yourls :) Much simpler for everyone! Thanks
