### ISSUE TITLE
Norwegian translation

### ISSUE THREAD

**Issue by armandg** [YOURLS/YOURLS.pot#35]
Hey, [here](https://github.com/armandg/YOURLSNO) is the Norwegian translation for YOURLS. This is the translation for Norwegian "Bokmål", not "Nynorsk", which is a separate written dialect.

**Comment by ozh** [comment]
Neat! Please open a pull request on https://github.com/YOURLS/awesome-yourls and get your translation listed there

Side question: I thought it was simply "no_NO", but from your translation I understand it's "nb_NO" and maybe "ny_NO" then ?

**Comment by armandg** [comment]
Cheers, will do a PR.

You are almost correct, the correct versions are "nb_NO" and "nn_NO".
