### ISSUE TITLE
Simplified Chinese (zh_CN) for YOURLS 1.7

### ISSUE THREAD

**Issue by ZvonimirSun** [YOURLS/YOURLS.pot#36]
https://github.com/ZvonimirSun/YOURLS-zh_CN
Simplified Chinese files for YOURLS 1.7。

I found the zh_CN files on [YOURLS/awesome-yourls](https://github.com/YOURLS/awesome-yourls) is still pointed to [guox/yourls-zh_CN](https://github.com/guox/yourls-zh_CN/) which is out of date and for YOURLS 1.6。

**Comment by LeoColomb** [comment]
Thanks for that @ZvonimirSun!
Could you then open a pull request on https://github.com/YOURLS/awesome-yourls with this remplacement? 👍

**Comment by ZvonimirSun** [comment]
@LeoColomb Sure, I have done that now.

[https://github.com/YOURLS/awesome-yourls/pull/36](https://github.com/YOURLS/awesome-yourls/pull/36)

**Comment by LeoColomb** [comment]
Thanks! Closing this in favor of that PR.
